# Generated by Django 3.0.5 on 2020-06-06 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroom_name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ticket', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('chatroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roulette.ChatRoom')),
                ('tags', models.ManyToManyField(to='roulette.Tag')),
            ],
        ),
    ]
