# Generated by Django 3.0.5 on 2020-06-06 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0003_auto_20200606_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='chatroom_id',
        ),
        migrations.AddField(
            model_name='person',
            name='chatroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roulette.ChatRoom'),
        ),
    ]
