# Generated by Django 3.0.5 on 2020-06-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0004_auto_20200606_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='occupied',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
