# Generated by Django 3.0.5 on 2020-06-06 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0005_auto_20200606_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='chatroom',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='roulette.ChatRoom'),
        ),
    ]
